"""
Shared fixtures.

The corpus is generated by `npm run seed:documents` and is git-ignored, so tests
that need it skip rather than fail when it is absent. A missing corpus is a
setup state, not a defect — but a test that silently passes without it would
hide a real regression, so the skip is explicit and names the command.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytesseract
import pytest

from app.config import get_settings

CORPUS_ROOT = Path(__file__).resolve().parents[3] / "db" / "seed" / "output"


@pytest.fixture(scope="session", autouse=True)
def _tesseract_configured():
    settings = get_settings()
    pytesseract.pytesseract.tesseract_cmd = settings.tesseract_cmd
    return settings


@pytest.fixture(scope="session")
def settings():
    return get_settings()


@pytest.fixture(scope="session")
def manifest():
    path = CORPUS_ROOT / "manifest.json"
    if not path.exists():
        pytest.skip("corpus absent — run `npm run seed:documents` from the repo root")
    return json.loads(path.read_text(encoding="utf-8"))


@pytest.fixture(scope="session")
def requires_tesseract(settings):
    if not settings.tesseract_available:
        pytest.skip(f"tesseract not installed at {settings.tesseract_cmd}")
    return True


def corpus_path(relative: str) -> Path:
    return CORPUS_ROOT / relative


def documents(manifest: dict, variant: str) -> list[dict]:
    return [d for d in manifest["documents"] if d["variant"] == variant]
