/**
 * KNOWN FRAUD PATTERNS
 * ====================
 *
 * The fraud patterns the Tier 1 rules are explicitly written against. Recall
 * measured here is an internal-consistency baseline — it demonstrates the engine
 * catches what it was designed to catch, and nothing more than that.
 *
 * The number that actually means something is recall against
 * `patterns.holdout.ts`, which was sealed before any rule code existed. The gap
 * between the two figures is this project's overfitting measure
 * (PROJECT_REPORT.md §7.1, §8).
 *
 * Quoting known recall on its own, in a demo or anywhere else, would be the exact
 * circular claim the holdout split exists to prevent.
 */

import type { KnownCase } from './types.js';

export const KNOWN_CASES: KnownCase[] = [
  {
    id: 'K-01-sibling-income-contradiction',
    behaviour:
      'Two siblings at one address with one guardian declare household incomes of ₹96,000 and ₹1,78,000. One certificate describes the household honestly; the other does not.',
    expectedRules: ['SIBLING_INCOME_CONTRADICTION'],
    shouldFlag: ['a1', 'a2'],
    applications: [
      {
        ref: 'a1',
        applicantName: 'Hariharan Muthusamy',
        guardianName: 'Muthusamy Govindaraj',
        guardianPhone: '9345112200',
        addressLine: '27 Kongu Nagar, Peelamedu',
        district: 'Coimbatore',
        pincode: '641004',
        declaredAnnualIncome: 96_000,
        declaredFamilySize: 5,
        certificateId: 'TN-CBE-2026-660214',
        issuingOffice: 'Coimbatore North Taluk Office',
        certificateIssueDate: '2026-06-02',
        applicationDate: '2026-06-15',
        cycle: '2026',
      },
      {
        ref: 'a2',
        applicantName: 'Gowri Muthusamy',
        guardianName: 'Muthusamy Govindaraj',
        guardianPhone: '9345112200',
        addressLine: '27 Kongu Nagar, Peelamedu',
        district: 'Coimbatore',
        pincode: '641004',
        declaredAnnualIncome: 178_000,
        declaredFamilySize: 5,
        certificateId: 'TN-CBE-2026-661885',
        issuingOffice: 'Coimbatore North Taluk Office',
        certificateIssueDate: '2026-06-05',
        applicationDate: '2026-06-18',
        cycle: '2026',
      },
    ],
  },

  {
    id: 'K-02-guardian-across-households',
    behaviour:
      'One guardian appears on two applications filed as separate households at different addresses, declaring ₹89,000 on one and ₹6,40,000 on the other.',
    expectedRules: ['GUARDIAN_INCOME_CONTRADICTION'],
    shouldFlag: ['b1', 'b2'],
    applications: [
      {
        ref: 'b1',
        applicantName: 'Deepak Anand',
        guardianName: 'Anand Krishnan',
        guardianPhone: '9840556677',
        addressLine: '19 Lake View Road',
        district: 'Madurai',
        pincode: '625002',
        declaredAnnualIncome: 89_000,
        declaredFamilySize: 4,
        certificateId: 'TN-MDU-2026-810556',
        issuingOffice: 'Madurai South Taluk Office',
        certificateIssueDate: '2026-05-30',
        applicationDate: '2026-06-14',
        cycle: '2026',
      },
      {
        ref: 'b2',
        applicantName: 'Nithya Anand',
        guardianName: 'Anand Krishnan',
        guardianPhone: '9445228811',
        addressLine: '88 South Main Street',
        district: 'Thanjavur',
        pincode: '612001',
        declaredAnnualIncome: 640_000,
        declaredFamilySize: 4,
        certificateId: 'TN-TNJ-2026-700344',
        issuingOffice: 'Thanjavur Taluk Office',
        certificateIssueDate: '2026-06-01',
        applicationDate: '2026-06-16',
        cycle: '2026',
      },
    ],
  },

  {
    id: 'K-03-address-cluster',
    behaviour:
      'Four applicants with no shared guardian, phone, or surname give the same address, all declaring incomes below the eligibility ceiling.',
    expectedRules: ['ADDRESS_CLUSTER_UNRELATED'],
    shouldFlag: ['c1', 'c2', 'c3', 'c4'],
    applications: [
      {
        ref: 'c1',
        applicantName: 'Praveen Kumar',
        guardianName: 'Kumar Anbazhagan',
        guardianPhone: '9791004411',
        addressLine: '18 Gandhi Road, Tambaram',
        district: 'Chengalpattu',
        pincode: '600045',
        declaredAnnualIncome: 88_000,
        declaredFamilySize: 5,
        certificateId: 'TN-CGL-2026-440112',
        issuingOffice: 'Tambaram Taluk Office',
        certificateIssueDate: '2026-05-14',
        applicationDate: '2026-06-02',
        cycle: '2026',
      },
      {
        ref: 'c2',
        applicantName: 'Sneha Balaji',
        guardianName: 'Balaji Venkatesh',
        guardianPhone: '9791225588',
        addressLine: '18 Gandhi Road, Tambaram',
        district: 'Chengalpattu',
        pincode: '600045',
        declaredAnnualIncome: 91_500,
        declaredFamilySize: 4,
        certificateId: 'TN-CGL-2026-441038',
        issuingOffice: 'Tambaram Taluk Office',
        certificateIssueDate: '2026-05-16',
        applicationDate: '2026-06-04',
        cycle: '2026',
      },
      {
        ref: 'c3',
        applicantName: 'Arun Prakash',
        guardianName: 'Prakash Mani',
        guardianPhone: '9944337712',
        addressLine: '18 Gandhi Road, Tambaram',
        district: 'Chengalpattu',
        pincode: '600045',
        declaredAnnualIncome: 79_000,
        declaredFamilySize: 6,
        certificateId: 'TN-CGL-2026-442901',
        issuingOffice: 'Tambaram Taluk Office',
        certificateIssueDate: '2026-05-19',
        applicationDate: '2026-06-07',
        cycle: '2026',
      },
      {
        ref: 'c4',
        applicantName: 'Meena Sundar',
        guardianName: 'Sundar Rajan',
        guardianPhone: '9600441199',
        addressLine: '18 Gandhi Road, Tambaram',
        district: 'Chengalpattu',
        pincode: '600045',
        declaredAnnualIncome: 84_000,
        declaredFamilySize: 5,
        certificateId: 'TN-CGL-2026-443377',
        issuingOffice: 'Tambaram Taluk Office',
        certificateIssueDate: '2026-05-21',
        applicationDate: '2026-06-09',
        cycle: '2026',
      },
    ],
  },

  {
    id: 'K-04-issuing-office-mismatch',
    behaviour:
      'One household, no relocation on record, holding certificates from two different taluk offices in the same cycle.',
    expectedRules: ['ISSUING_OFFICE_MISMATCH'],
    shouldFlag: ['d1', 'd2'],
    applications: [
      {
        ref: 'd1',
        applicantName: 'Aravind Jayakumar',
        guardianName: 'Jayakumar Nagarajan',
        guardianPhone: '9840990011',
        addressLine: '23 Kamban Street',
        district: 'Tiruchirappalli',
        pincode: '620001',
        declaredAnnualIncome: 89_000,
        declaredFamilySize: 4,
        certificateId: 'TN-TRY-2026-220145',
        issuingOffice: 'Tiruchirappalli West Taluk Office',
        certificateIssueDate: '2026-06-06',
        applicationDate: '2026-06-19',
        cycle: '2026',
      },
      {
        ref: 'd2',
        applicantName: 'Nandhini Jayakumar',
        guardianName: 'Jayakumar Nagarajan',
        guardianPhone: '9840990011',
        addressLine: '23 Kamban Street',
        district: 'Tiruchirappalli',
        pincode: '620001',
        declaredAnnualIncome: 91_500,
        declaredFamilySize: 4,
        certificateId: 'TN-TRY-2026-220198',
        issuingOffice: 'Tiruchirappalli East Taluk Office',
        certificateIssueDate: '2026-06-07',
        applicationDate: '2026-06-20',
        cycle: '2026',
      },
    ],
  },

  {
    id: 'K-05-deadline-proximity-corroborated',
    behaviour:
      'A household with a genuine income contradiction whose certificates were also obtained days before the deadline. Deadline proximity is meaningless alone; here it has corroboration.',
    expectedRules: ['SIBLING_INCOME_CONTRADICTION', 'DEADLINE_PROXIMITY'],
    shouldFlag: ['e1', 'e2'],
    applications: [
      {
        ref: 'e1',
        applicantName: 'Rohit Ilango',
        guardianName: 'Ilango Perumal',
        guardianPhone: '9345009911',
        addressLine: '55 VOC Street',
        district: 'Tirunelveli',
        pincode: '627001',
        declaredAnnualIncome: 94_000,
        declaredFamilySize: 4,
        certificateId: 'TN-TVL-2026-341902',
        issuingOffice: 'Tirunelveli Taluk Office',
        certificateIssueDate: '2026-07-24',
        applicationDate: '2026-07-29',
        cycle: '2026',
      },
      {
        ref: 'e2',
        applicantName: 'Kavya Ilango',
        guardianName: 'Ilango Perumal',
        guardianPhone: '9345009911',
        addressLine: '55 VOC Street',
        district: 'Tirunelveli',
        pincode: '627001',
        declaredAnnualIncome: 232_000,
        declaredFamilySize: 4,
        certificateId: 'TN-TVL-2026-341955',
        issuingOffice: 'Tirunelveli Taluk Office',
        certificateIssueDate: '2026-07-26',
        applicationDate: '2026-07-30',
        cycle: '2026',
      },
    ],
  },

  {
    id: 'K-06-guardian-initial-still-resolves',
    behaviour:
      'Siblings whose father is written in full on one application and as an initial plus surname on the other. Resolution must still merge them for the contradiction to be visible.',
    expectedRules: ['SIBLING_INCOME_CONTRADICTION'],
    shouldFlag: ['f1', 'f2'],
    applications: [
      {
        ref: 'f1',
        applicantName: 'Ashwin Venkat',
        guardianName: 'Venkat Ramachandran',
        guardianPhone: '9500334422',
        addressLine: '108 Trichy Main Road',
        district: 'Salem',
        pincode: '636001',
        declaredAnnualIncome: 92_000,
        declaredFamilySize: 4,
        certificateId: 'TN-SLM-2026-905611',
        issuingOffice: 'Salem Taluk Office',
        certificateIssueDate: '2026-06-03',
        applicationDate: '2026-06-16',
        cycle: '2026',
      },
      {
        ref: 'f2',
        applicantName: 'Aparna Venkat',
        guardianName: 'V. Ramachandran',
        guardianPhone: '9500334422',
        addressLine: '108 Trichy Main Rd',
        district: 'Salem',
        pincode: '636001',
        declaredAnnualIncome: 214_000,
        declaredFamilySize: 4,
        certificateId: 'TN-SLM-2026-906033',
        issuingOffice: 'Salem Taluk Office',
        certificateIssueDate: '2026-06-04',
        applicationDate: '2026-06-17',
        cycle: '2026',
      },
    ],
  },

  {
    id: 'K-07-three-sibling-outlier',
    behaviour:
      'Three siblings in one household. Two agree at roughly ₹95,000; the third declares ₹1,78,000. The outlier is visible only against its siblings.',
    expectedRules: ['SIBLING_INCOME_CONTRADICTION'],
    shouldFlag: ['g1', 'g2', 'g3'],
    applications: [
      {
        ref: 'g1',
        applicantName: 'Karthik Raman',
        guardianName: 'Raman Subramaniam',
        guardianPhone: '9840112233',
        addressLine: '14 Bharathi Street, Ayanavaram',
        district: 'Chennai',
        pincode: '600023',
        declaredAnnualIncome: 96_000,
        declaredFamilySize: 5,
        certificateId: 'TN-CHN-2026-118842',
        issuingOffice: 'Ayanavaram Taluk Office',
        certificateIssueDate: '2026-06-11',
        applicationDate: '2026-06-20',
        cycle: '2026',
      },
      {
        ref: 'g2',
        applicantName: 'Gowri Raman',
        guardianName: 'Raman Subramaniam',
        guardianPhone: '9840112233',
        addressLine: '14 Bharathi Street, Ayanavaram',
        district: 'Chennai',
        pincode: '600023',
        declaredAnnualIncome: 92_500,
        declaredFamilySize: 5,
        certificateId: 'TN-CHN-2026-118901',
        issuingOffice: 'Ayanavaram Taluk Office',
        certificateIssueDate: '2026-06-12',
        applicationDate: '2026-06-21',
        cycle: '2026',
      },
      {
        ref: 'g3',
        applicantName: 'Bhuvana Raman',
        guardianName: 'Raman Subramaniam',
        guardianPhone: '9840112233',
        addressLine: '14 Bharathi Street, Ayanavaram',
        district: 'Chennai',
        pincode: '600023',
        declaredAnnualIncome: 178_000,
        declaredFamilySize: 5,
        certificateId: 'TN-CHN-2026-119044',
        issuingOffice: 'Ayanavaram Taluk Office',
        certificateIssueDate: '2026-06-13',
        applicationDate: '2026-06-22',
        cycle: '2026',
      },
    ],
  },
];

export const KNOWN_APPLICATION_COUNT = KNOWN_CASES.reduce(
  (n, c) => n + c.applications.length,
  0,
);

export const KNOWN_EXPECTED_FLAG_COUNT = KNOWN_CASES.reduce((n, c) => n + c.shouldFlag.length, 0);
